import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.register': 'Register',
    'nav.vote': 'Vote',
    'nav.results': 'Results',
    'nav.verify': 'Verify',
    'nav.help': 'Help',
    
    // Home
    'home.title': 'Digital India Voting',
    'home.subtitle': 'Experience the future of democracy in India. Secure, transparent, and accessible voting for every citizen, powered by blockchain technology.',
    'home.registerBtn': 'Register to Vote',
    'home.voteBtn': 'Cast Your Vote',
    'home.whyTitle': 'Why Choose Digital India Voting?',
    'home.whySubtitle': 'Built with cutting-edge technology for India\'s democratic future',
    'home.security': 'Bank-Level Security',
    'home.securityDesc': 'Advanced encryption and multi-layer security protocols protect every vote',
    'home.transparent': 'Transparent Process',
    'home.transparentDesc': 'Blockchain-verified voting with real-time audit trails',
    'home.accessible': 'Accessible for All',
    'home.accessibleDesc': 'Designed for universal accessibility and ease of use',
    'home.voters': 'Eligible Voters',
    'home.uptime': 'System Uptime',
    'home.accuracy': 'Vote Accuracy',
    'home.ctaTitle': 'Ready to Exercise Your Democratic Right?',
    'home.ctaSubtitle': 'Join millions of Indian citizens participating in secure digital democracy',
    'home.getStarted': 'Get Started Today',
    'home.learnMore': 'Learn More',
    
    // Registration
    'register.title': 'Voter Registration',
    'register.subtitle': 'Register to participate in secure digital democracy',
    'register.personalInfo': 'Personal Information',
    'register.infoDesc': 'All information is encrypted and securely stored',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.dob': 'Date of Birth',
    'register.aadhar': 'Aadhar Number',
    'register.address': 'Street Address',
    'register.city': 'City',
    'register.state': 'State',
    'register.zip': 'ZIP Code',
    'register.email': 'Email Address',
    'register.phone': 'Phone Number',
    'register.terms': 'I agree to the terms and conditions and confirm that all information provided is accurate',
    'register.submit': 'Submit Registration',
    'register.security': 'Security & Privacy',
    'register.securityPoint1': 'All data is encrypted with AES-256',
    'register.securityPoint2': 'Information used only for voter verification',
    'register.securityPoint3': 'Aadhar stored securely and separately',
    'register.securityPoint4': 'Regular security audits performed',
    'register.requirements': 'Requirements',
    'register.req1': 'Must be 18 years or older',
    'register.req2': 'Valid 12-digit Aadhar Number',
    'register.req3': 'Current residential address',
    'register.req4': 'Valid email for notifications',
    'register.needHelp': 'Need Help?',
    'register.helpDesc': 'Contact our support team for assistance',
    'register.getSupport': 'Get Support',
    
    // Voting
    'vote.regRequired': 'Voter Registration Required',
    'vote.regDesc': 'You must be registered to vote before accessing the voting booth',
    'vote.regCheck': 'Registration Status Check',
    'vote.regQuestion': 'Are you already registered to vote in this jurisdiction?',
    'vote.yesReg': 'Yes, I\'m Registered - Proceed to Vote',
    'vote.noReg': 'No, I Need to Register First',
    'vote.regNote1': 'Registration is required by law to participate in elections.',
    'vote.regNote2': 'If you\'re unsure of your status, please register to ensure your eligibility.',
    'vote.verifyTitle': 'Verify Your Identity',
    'vote.verifyDesc': 'Please provide your registered details to proceed',
    'vote.fullName': 'Full Name (as registered)',
    'vote.back': 'Back',
    'vote.verifyContinue': 'Verify & Continue',
    'vote.verifyNote': 'Your information will be verified against voter registration records.',
    'vote.complete': 'Voting Complete!',
    'vote.completeDesc': 'Your ballot has been successfully cast and recorded',
    'vote.confirmDetails': 'Confirmation Details',
    'vote.ballotId': 'Ballot ID',
    'vote.timestamp': 'Timestamp',
    'vote.encryption': 'Encryption',
    'vote.viewReceipt': 'View Receipt & Verify Vote',
    'vote.downloadReceipt': 'Download Receipt',
    'vote.returnHome': 'Return to Home',
    'vote.selectionRequired': 'Selection Required',
    'vote.selectionDesc': 'Please make a selection before continuing.',
    'vote.next': 'Next',
    'vote.previous': 'Previous',
    'vote.submitBallot': 'Submit Ballot',
    
    // Verification
    'verify.title': 'Vote Verification',
    'verify.subtitle': 'Verify your ballot and check voting status',
    'verify.enterBallot': 'Enter Your Ballot ID',
    'verify.ballotIdLabel': 'Ballot ID',
    'verify.ballotPlaceholder': 'Enter your ballot ID (e.g., VT-2024-XXXXXX)',
    'verify.verifyBtn': 'Verify Vote',
    'verify.lostReceipt': 'Lost your ballot ID?',
    'verify.lostReceiptBtn': 'Retrieve Ballot ID',
    'verify.result': 'Verification Results',
    'verify.status': 'Status',
    'verify.voteRecorded': 'Your vote has been recorded and verified in the system',
    'verify.downloadCert': 'Download Certificate',
    'verify.share': 'Share Verification',
    'verify.howTitle': 'How Verification Works',
    'verify.howDesc': 'Our blockchain-based system ensures every vote is verifiable',
    'verify.howPoint1': 'Each vote receives a unique Ballot ID',
    'verify.howPoint2': 'Votes are encrypted using AES-256',
    'verify.howPoint3': 'Blockchain records are immutable',
    'verify.howPoint4': 'Real-time verification available',
    'verify.receiptTitle': 'About Your Receipt',
    'verify.receiptDesc': 'Your voting receipt contains important information',
    'verify.receiptPoint1': 'Keep your Ballot ID safe and secure',
    'verify.receiptPoint2': 'Used to verify your vote was counted',
    'verify.receiptPoint3': 'Cannot be used to change your vote',
    'verify.receiptPoint4': 'Sharing is safe - votes remain anonymous',
    'verify.lostTitle': 'Lost Receipt Lookup',
    'verify.lostDesc': 'Enter your registered details to retrieve your Ballot ID',
    'verify.findBallot': 'Find Ballot ID',
    'verify.yourBallotId': 'Your Ballot ID:',
    'verify.useBallot': 'Use this ID to verify your vote below',
    'verify.receiptHeader': 'Vote Receipt',
    'verify.receiptSuccessDesc': 'Your ballot has been successfully recorded',
    'verify.officialReceipt': 'Official Voting Receipt',
    'verify.savePlease': 'Please save this information for verification',
    'verify.applied': 'Applied',
    'verify.recorded': 'Recorded',
    'verify.confirmed': 'Confirmed',
    'verify.important': 'Important Information',
    'verify.keepSafe': 'Keep this Ballot ID safe for verification',
    'verify.canVerify': 'You can verify your vote at any time using this ID',
    'verify.encrypted': 'Your vote is encrypted and anonymous',
    'verify.resultsAfter': 'Results will be available after election closes',
    'verify.proceedVerify': 'Proceed to Verify Vote',
    
    // Common
    'common.selectState': 'Select state',
    'common.searching': 'Searching...',
    'common.loading': 'Loading...',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.register': 'पंजीकरण',
    'nav.vote': 'मतदान',
    'nav.results': 'परिणाम',
    'nav.verify': 'सत्यापन',
    'nav.help': 'सहायता',
    
    // Home
    'home.title': 'डिजिटल इंडिया मतदान',
    'home.subtitle': 'भारत में लोकतंत्र के भविष्य का अनुभव करें। ब्लॉकचेन तकनीक द्वारा संचालित प्रत्येक नागरिक के लिए सुरक्षित, पारदर्शी और सुलभ मतदान।',
    'home.registerBtn': 'मतदान के लिए पंजीकरण करें',
    'home.voteBtn': 'अपना वोट डालें',
    'home.whyTitle': 'डिजिटल इंडिया मतदान क्यों चुनें?',
    'home.whySubtitle': 'भारत के लोकतांत्रिक भविष्य के लिए अत्याधुनिक तकनीक के साथ निर्मित',
    'home.security': 'बैंक-स्तरीय सुरक्षा',
    'home.securityDesc': 'उन्नत एन्क्रिप्शन और बहु-स्तरीय सुरक्षा प्रोटोकॉल हर वोट की रक्षा करते हैं',
    'home.transparent': 'पारदर्शी प्रक्रिया',
    'home.transparentDesc': 'वास्तविक समय ऑडिट ट्रेल्स के साथ ब्लॉकचेन-सत्यापित मतदान',
    'home.accessible': 'सभी के लिए सुलभ',
    'home.accessibleDesc': 'सार्वभौमिक पहुंच और उपयोग में आसानी के लिए डिज़ाइन किया गया',
    'home.voters': 'पात्र मतदाता',
    'home.uptime': 'सिस्टम अपटाइम',
    'home.accuracy': 'वोट सटीकता',
    'home.ctaTitle': 'अपने लोकतांत्रिक अधिकार का प्रयोग करने के लिए तैयार हैं?',
    'home.ctaSubtitle': 'लाखों भारतीय नागरिकों के साथ सुरक्षित डिजिटल लोकतंत्र में भाग लें',
    'home.getStarted': 'आज ही शुरू करें',
    'home.learnMore': 'और जानें',
    
    // Registration
    'register.title': 'मतदाता पंजीकरण',
    'register.subtitle': 'सुरक्षित डिजिटल लोकतंत्र में भाग लेने के लिए पंजीकरण करें',
    'register.personalInfo': 'व्यक्तिगत जानकारी',
    'register.infoDesc': 'सभी जानकारी एन्क्रिप्टेड और सुरक्षित रूप से संग्रहीत है',
    'register.firstName': 'पहला नाम',
    'register.lastName': 'अंतिम नाम',
    'register.dob': 'जन्म तिथि',
    'register.aadhar': 'आधार संख्या',
    'register.address': 'पता',
    'register.city': 'शहर',
    'register.state': 'राज्य',
    'register.zip': 'पिन कोड',
    'register.email': 'ईमेल पता',
    'register.phone': 'फ़ोन नंबर',
    'register.terms': 'मैं नियमों और शर्तों से सहमत हूं और पुष्टि करता हूं कि प्रदान की गई सभी जानकारी सटीक है',
    'register.submit': 'पंजीकरण जमा करें',
    'register.security': 'सुरक्षा और गोपनीयता',
    'register.securityPoint1': 'सभी डेटा AES-256 से एन्क्रिप्ट किया गया है',
    'register.securityPoint2': 'जानकारी केवल मतदाता सत्यापन के लिए उपयोग की जाती है',
    'register.securityPoint3': 'आधार सुरक्षित रूप से और अलग से संग्रहीत',
    'register.securityPoint4': 'नियमित सुरक्षा ऑडिट किए जाते हैं',
    'register.requirements': 'आवश्यकताएं',
    'register.req1': '18 वर्ष या उससे अधिक आयु होनी चाहिए',
    'register.req2': 'वैध 12 अंकों का आधार नंबर',
    'register.req3': 'वर्तमान आवासीय पता',
    'register.req4': 'सूचनाओं के लिए वैध ईमेल',
    'register.needHelp': 'सहायता चाहिए?',
    'register.helpDesc': 'सहायता के लिए हमारी सहायता टीम से संपर्क करें',
    'register.getSupport': 'सहायता प्राप्त करें',
    
    // Voting
    'vote.regRequired': 'मतदाता पंजीकरण आवश्यक',
    'vote.regDesc': 'मतदान बूथ तक पहुंचने से पहले आपको मतदान के लिए पंजीकृत होना चाहिए',
    'vote.regCheck': 'पंजीकरण स्थिति जांच',
    'vote.regQuestion': 'क्या आप पहले से इस क्षेत्राधिकार में मतदान के लिए पंजीकृत हैं?',
    'vote.yesReg': 'हां, मैं पंजीकृत हूं - मतदान के लिए आगे बढ़ें',
    'vote.noReg': 'नहीं, मुझे पहले पंजीकरण करने की आवश्यकता है',
    'vote.regNote1': 'चुनावों में भाग लेने के लिए कानून द्वारा पंजीकरण आवश्यक है।',
    'vote.regNote2': 'यदि आप अपनी स्थिति के बारे में निश्चित नहीं हैं, तो कृपया अपनी पात्रता सुनिश्चित करने के लिए पंजीकरण करें।',
    'vote.verifyTitle': 'अपनी पहचान सत्यापित करें',
    'vote.verifyDesc': 'कृपया आगे बढ़ने के लिए अपना पंजीकृत विवरण प्रदान करें',
    'vote.fullName': 'पूरा नाम (जैसा पंजीकृत है)',
    'vote.back': 'वापस',
    'vote.verifyContinue': 'सत्यापित करें और जारी रखें',
    'vote.verifyNote': 'आपकी जानकारी मतदाता पंजीकरण रिकॉर्ड के विरुद्ध सत्यापित की जाएगी।',
    'vote.complete': 'मतदान पूर्ण!',
    'vote.completeDesc': 'आपका बैलेट सफलतापूर्वक डाला और रिकॉर्ड किया गया है',
    'vote.confirmDetails': 'पुष्टिकरण विवरण',
    'vote.ballotId': 'बैलेट आईडी',
    'vote.timestamp': 'समय टिकट',
    'vote.encryption': 'एन्क्रिप्शन',
    'vote.viewReceipt': 'रसीद देखें और वोट सत्यापित करें',
    'vote.downloadReceipt': 'रसीद डाउनलोड करें',
    'vote.returnHome': 'होम पर वापस जाएं',
    'vote.selectionRequired': 'चयन आवश्यक',
    'vote.selectionDesc': 'कृपया जारी रखने से पहले एक चयन करें।',
    'vote.next': 'अगला',
    'vote.previous': 'पिछला',
    'vote.submitBallot': 'बैलेट जमा करें',
    
    // Verification
    'verify.title': 'वोट सत्यापन',
    'verify.subtitle': 'अपना बैलेट सत्यापित करें और मतदान स्थिति जांचें',
    'verify.enterBallot': 'अपना बैलेट आईडी दर्ज करें',
    'verify.ballotIdLabel': 'बैलेट आईडी',
    'verify.ballotPlaceholder': 'अपना बैलेट आईडी दर्ज करें (उदा., VT-2024-XXXXXX)',
    'verify.verifyBtn': 'वोट सत्यापित करें',
    'verify.lostReceipt': 'अपना बैलेट आईडी खो गया?',
    'verify.lostReceiptBtn': 'बैलेट आईडी पुनः प्राप्त करें',
    'verify.result': 'सत्यापन परिणाम',
    'verify.status': 'स्थिति',
    'verify.voteRecorded': 'आपका वोट सिस्टम में रिकॉर्ड और सत्यापित किया गया है',
    'verify.downloadCert': 'प्रमाणपत्र डाउनलोड करें',
    'verify.share': 'सत्यापन साझा करें',
    'verify.howTitle': 'सत्यापन कैसे काम करता है',
    'verify.howDesc': 'हमारी ब्लॉकचेन-आधारित प्रणाली सुनिश्चित करती है कि प्रत्येक वोट सत्यापन योग्य है',
    'verify.howPoint1': 'प्रत्येक वोट को एक अद्वितीय बैलेट आईडी प्राप्त होता है',
    'verify.howPoint2': 'वोट AES-256 का उपयोग करके एन्क्रिप्ट किए जाते हैं',
    'verify.howPoint3': 'ब्लॉकचेन रिकॉर्ड अपरिवर्तनीय हैं',
    'verify.howPoint4': 'वास्तविक समय सत्यापन उपलब्ध',
    'verify.receiptTitle': 'आपकी रसीद के बारे में',
    'verify.receiptDesc': 'आपकी मतदान रसीद में महत्वपूर्ण जानकारी है',
    'verify.receiptPoint1': 'अपना बैलेट आईडी सुरक्षित रखें',
    'verify.receiptPoint2': 'आपके वोट को गिना गया था यह सत्यापित करने के लिए उपयोग किया जाता है',
    'verify.receiptPoint3': 'आपका वोट बदलने के लिए उपयोग नहीं किया जा सकता',
    'verify.receiptPoint4': 'साझा करना सुरक्षित है - वोट गुमनाम रहते हैं',
    'verify.lostTitle': 'खोई हुई रसीद खोज',
    'verify.lostDesc': 'अपना बैलेट आईडी पुनः प्राप्त करने के लिए अपना पंजीकृत विवरण दर्ज करें',
    'verify.findBallot': 'बैलेट आईडी खोजें',
    'verify.yourBallotId': 'आपका बैलेट आईडी:',
    'verify.useBallot': 'नीचे अपना वोट सत्यापित करने के लिए इस आईडी का उपयोग करें',
    'verify.receiptHeader': 'वोट रसीद',
    'verify.receiptSuccessDesc': 'आपका बैलेट सफलतापूर्वक रिकॉर्ड किया गया है',
    'verify.officialReceipt': 'आधिकारिक मतदान रसीद',
    'verify.savePlease': 'कृपया सत्यापन के लिए यह जानकारी सहेजें',
    'verify.applied': 'लागू',
    'verify.recorded': 'रिकॉर्ड किया गया',
    'verify.confirmed': 'पुष्टि की गई',
    'verify.important': 'महत्वपूर्ण जानकारी',
    'verify.keepSafe': 'सत्यापन के लिए इस बैलेट आईडी को सुरक्षित रखें',
    'verify.canVerify': 'आप इस आईडी का उपयोग करके किसी भी समय अपने वोट को सत्यापित कर सकते हैं',
    'verify.encrypted': 'आपका वोट एन्क्रिप्ट और गुमनाम है',
    'verify.resultsAfter': 'चुनाव बंद होने के बाद परिणाम उपलब्ध होंगे',
    'verify.proceedVerify': 'वोट सत्यापित करने के लिए आगे बढ़ें',
    
    // Common
    'common.selectState': 'राज्य चुनें',
    'common.searching': 'खोज रहा है...',
    'common.loading': 'लोड हो रहा है...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};